# See more config options https://github.com/foundry-rs/foundry/tree/master/config[rpc_endpoints]
[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

fs_permissions = [{ access = "read-write", path = "./"}]

[profile.network.mumbai] # network name, used to identify the chain in etherscan
mumbai = "${RPC_URL}"

[profile.polygonscan]
mumbai = { key = "${POLYGONSCAN_API_KEY}" }

[etherscan]
mumbai = { key = "${POLYGONSCAN_API_KEY}" }
